# Using Pre-trained Word Embeddings

This notebook will demonstrate how to use pre-trained word embeddings.

To see why word embeddings are useful, it's worth comparing them to the alternative.
Without word embeddings, we might represent each word with a one-hot vector `[0, ...,0, 1, 0, ... 0]`, that takes value `1` at the index corresponding to the appropriate vocabulary word, 
and value `0` everywhere else. 
The weight matrices connecting our word-level inputs to the network's hidden layers would each be $v \times h$,
where $v$ is the size of the vocabulary and $h$ is the size of the hidden layer. 
With 100,000 words feeding into an LSTM layer with $1000$ nodes, the model would need to learn
$4$ different weight matrices (one for each of the LSTM gates), each with 100M weights, and thus 400 million parameters in total.

Fortunately, it turns out that a number of efficient techniques 
can quickly discover broadly useful word embeddings in an *unsupervised* manner.
These embeddings map each word onto a low-dimensional vector $w \in R^d$ with $d$ commonly chosen to be roughly $100$.
Intuitively, these embeddings are chosen based on the contexts in which words appear. 
Words that appear in similar contexts (like "tennis" and "racquet") should have similar embeddings
while words that do not like (like "rat" and "gourmet") should have dissimilar embeddings.

Practitioners of deep learning for NLP typically inititalize their models 
using *pretrained* word embeddings, bringing in outside information, and reducing the number of parameters that a neural network needs to learn from scratch.


Two popular word embeddings are Word2Vec and fastText. 
The following examples uses pre-trained word embeddings drawn from the following sources:

* Word2Vec https://arxiv.org/abs/1301.3781
* fastText project website：https://fasttext.cc/

To begin, let's first import a few packages that we'll need for this example:

In [1]:
import mxnet as mx
from mxnet import gluon, nd
from mxnet.gluon import rnn, nn
import gluonnlp as nlp
import re
import d2l

import warnings
warnings.filterwarnings('ignore')

## Pre-trained Word Embeddings

GluonNLP provides a number of pre-trained Word Embeddings.

In [2]:
nlp.embedding.list_sources('fasttext')[:5]

['crawl-300d-2M', 'crawl-300d-2M-subword', 'wiki.aa', 'wiki.ab', 'wiki.ace']

For simplicity of demonstration, we use a smaller word embedding file, such as
the 50-dimensional one.

In [3]:
emb = nlp.embedding.create('fasttext', source='wiki.en')

### Word Similarity

Given an input word, we can find the nearest word from
the vocabulary by similarity. The
similarity between any pair of words can be represented by the cosine similarity
of their vectors.

In [4]:
def norm_vecs_by_row(x):
    return x / nd.sqrt(nd.sum(x * x, axis=1) + 1E-10).reshape((-1,1))

In [5]:
def get_knn(emb, k, word):
    word_vec = emb[word].reshape((-1, 1))
    vocab_vecs = norm_vecs_by_row(emb.idx_to_vec)
    dot_prod = nd.dot(vocab_vecs, word_vec)
    indices = nd.topk(dot_prod.reshape((len(emb.idx_to_token), )), k=k+1, ret_typ='indices')
    indices = [int(i.asscalar()) for i in indices]
    return [emb.idx_to_token[i] for i in indices[1:]] # Remove input tokens.

Let us find the 5 most similar words of 'baby' from the vocabulary (size:
400,000 words).

In [6]:
get_knn(emb, 5, 'baby')

['babies', 'newborn', 'baby…', 'mom', 'toddler']

We can verify the cosine similarity of vectors of 'baby' and 'babies'.

In [7]:
from mxnet import nd
def cos_sim(x, y):
    return nd.dot(x, y) / (nd.norm(x) * nd.norm(y))

cos_sim(emb['baby'], emb['babies'])


[0.76009405]
<NDArray 1 @cpu(0)>

### Word Analogy

We can also apply pre-trained word embeddings to the word
analogy problem. 

For instance, "man : woman :: son : daughter" is an analogy.

The word analogy completion problem is defined as: for analogy 'a : b :: c : d',
given the first three words 'a', 'b', 'c', find 'd'. The idea is to find the
most similar word vector for vec('c') + (vec('b')-vec('a')).

In this example, we will find words by analogy from the 400,000 indexed words in `vocab`.

In [8]:
def get_top_k_by_analogy(emb, k, word1, word2, word3):
    word_vecs = emb[word1, word2, word3]
    word_diff = (word_vecs[1] - word_vecs[0] + word_vecs[2]).reshape((-1, 1))
    vocab_vecs = norm_vecs_by_row(emb.idx_to_vec)
    dot_prod = nd.dot(vocab_vecs, word_diff)
    indices = nd.topk(dot_prod.reshape((len(emb.idx_to_token), )), k=k, ret_typ='indices')
    indices = [int(i.asscalar()) for i in indices]
    return [emb.idx_to_token[i] for i in indices]

Complete word analogy 'man : woman :: son :'.

In [9]:
get_top_k_by_analogy(emb, 1, 'man', 'woman', 'son')

['daughter']

# Text Classification and Data Sets

Text classification is a common task in natural language processing, which transforms a sequence of text of indefinite length into a category of text.

## Text Sentiment Classification Data

Use Stanford's Large Movie Review Dataset as the data set for text sentiment classification.
- Contains parts for training and testing purposes, each containing 25,000 movie reviews downloaded from IMDb
- In each data set, the number of comments labeled as "positive" and "negative" is equal.

## Dataset in `gluon`

Datasets in Gluon have the following basic structure:

``` python
class Dataset(object):
    def __getitem__(self, idx):
        ...
    
    def __len__(self):
        ...

    def transform(self, fn, lazy=True):
        # Returns a new dataset with each sample
        # transformed by the function `fn`.
```

We can make list-like Python object (ie. that implements `__getitem__` meaning it  subscripted like `x[0]` etc.),
into a `gluon` `Dataset` by wrapping it, using `gluon.data.SimpleDataset` as follows:

In [10]:
def tokenize_while_preserving_label(sample):
    sentence, label = sample
    return sentence.split(), label

train_dataset, test_dataset = [nlp.data.IMDB(segment=segment).transform(
    tokenize_while_preserving_label, lazy=False)
    for segment in ('train', 'test')]

In [11]:
print(train_dataset[0])

(['Bromwell', 'High', 'is', 'a', 'cartoon', 'comedy.', 'It', 'ran', 'at', 'the', 'same', 'time', 'as', 'some', 'other', 'programs', 'about', 'school', 'life,', 'such', 'as', '"Teachers".', 'My', '35', 'years', 'in', 'the', 'teaching', 'profession', 'lead', 'me', 'to', 'believe', 'that', 'Bromwell', "High's", 'satire', 'is', 'much', 'closer', 'to', 'reality', 'than', 'is', '"Teachers".', 'The', 'scramble', 'to', 'survive', 'financially,', 'the', 'insightful', 'students', 'who', 'can', 'see', 'right', 'through', 'their', 'pathetic', "teachers'", 'pomp,', 'the', 'pettiness', 'of', 'the', 'whole', 'situation,', 'all', 'remind', 'me', 'of', 'the', 'schools', 'I', 'knew', 'and', 'their', 'students.', 'When', 'I', 'saw', 'the', 'episode', 'in', 'which', 'a', 'student', 'repeatedly', 'tried', 'to', 'burn', 'down', 'the', 'school,', 'I', 'immediately', 'recalled', '.........', 'at', '..........', 'High.', 'A', 'classic', 'line:', 'INSPECTOR:', "I'm", 'here', 'to', 'sack', 'one', 'of', 'your', '

In [12]:
def get_text(text, label):
    return text
train_tokens = train_dataset.transform(get_text)

import itertools
vocab = nlp.Vocab(nlp.data.count_tokens(itertools.chain.from_iterable(train_tokens)), min_freq=10)
print(vocab)
print(vocab.idx_to_token[:10] + ["..."])

Vocab(size=28740, unk="<unk>", reserved="['<pad>', '<bos>', '<eos>']")
['<unk>', '<pad>', '<bos>', '<eos>', 'the', 'a', 'and', 'of', 'to', 'is', '...']


In [13]:
# `length_clip` takes as input a list and outputs a list with maximum length 500.
length_clip = nlp.data.ClipSequence(500)

def preprocess(data, label):
    label = int(label > 5)
    data = vocab[length_clip(data)]
    return [data, label]


train_dataset = train_dataset.transform(preprocess)
test_dataset = test_dataset.transform(preprocess)
print(train_dataset[0])

[[0, 2720, 9, 5, 1400, 1352, 58, 2225, 33, 4, 171, 85, 17, 48, 82, 9137, 44, 520, 778, 140, 17, 0, 361, 7185, 193, 10, 4, 5819, 8968, 495, 86, 8, 265, 12, 0, 0, 2638, 9, 80, 2646, 8, 899, 72, 9, 0, 21, 0, 8, 2718, 0, 4, 7999, 1898, 37, 66, 69, 259, 150, 57, 1710, 0, 0, 4, 0, 7, 4, 215, 5442, 39, 2989, 86, 7, 4, 8660, 11, 638, 6, 57, 9156, 285, 11, 209, 4, 484, 10, 64, 5, 1839, 4580, 765, 8, 4401, 217, 4, 3156, 11, 1371, 19648, 0, 33, 0, 27132, 135, 443, 7613, 0, 162, 227, 8, 14323, 34, 7, 119, 0, 0, 18376, 8, 0, 27132, 11, 546, 12, 104, 2044, 7, 68, 879, 100, 12, 0, 2720, 9, 239, 0, 257, 5, 3155, 12, 14, 0], 1]


#### `gluonnlp.data.batchify.Pad`

`gluonnlp.data.batchify.Pad` can be instantiated with the padding value.
The resulting function takes a list of variable length lists (or NDArrays or numpy arrays)
as input and returns a single NDArray where all shorter inputs are padded to the length
of the maximum length input element.

In [14]:
print(len(train_dataset[0][0]), len(train_dataset[1][0]))

140 428


In [15]:
# Pad data, stack label and lengths
pad_val = vocab[vocab.padding_token]
batchify_fn = nlp.data.batchify.Tuple(
    nlp.data.batchify.Pad(axis=0, ret_length=True, pad_val=pad_val),
    nlp.data.batchify.Stack(dtype='float32'))
print('pad_val:', pad_val)

pad_val: 1


In [16]:
batchify_fn([train_dataset[0], train_dataset[1], train_dataset[2]])

((
  [[0.0000e+00 2.7200e+03 9.0000e+00 ... 1.0000e+00 1.0000e+00 1.0000e+00]
   [0.0000e+00 9.0800e+02 0.0000e+00 ... 8.0000e+00 3.3700e+02 2.2630e+03]
   [1.1217e+04 1.7181e+04 3.2000e+01 ... 1.0000e+00 1.0000e+00 1.0000e+00]]
  <NDArray 3x428 @cpu_shared(0)>, 
  [140 428 147]
  <NDArray 3 @cpu_shared(0)>), 
 [1. 1. 1.]
 <NDArray 3 @cpu_shared(0)>)

#### `gluon.data.DataLoader`

Manually sampling sentences from the dataset and applying the pad function may be bothersome.
`gluon.data.DataLoader` automates this process.

In [17]:
print(gluon.data.DataLoader.__doc__)

Loads data from a dataset and returns mini-batches of data.

    Parameters
    ----------
    dataset : Dataset
        Source dataset. Note that numpy and mxnet arrays can be directly used
        as a Dataset.
    batch_size : int
        Size of mini-batch.
    shuffle : bool
        Whether to shuffle the samples.
    sampler : Sampler
        The sampler to use. Either specify sampler or shuffle, not both.
    last_batch : {'keep', 'discard', 'rollover'}
        How to handle the last batch if batch_size does not evenly divide
        `len(dataset)`.

        keep - A batch with less samples than previous batches is returned.
        discard - The last batch is discarded if its incomplete.
        rollover - The remaining samples are rolled over to the next epoch.
    batch_sampler : Sampler
        A sampler that returns mini-batches. Do not specify batch_size,
        shuffle, sampler, and last_batch if batch_sampler is specified.
    batchify_fn : callable
        Callback fun

In [18]:
batch_size = 128
data_loader = gluon.data.DataLoader(train_dataset, batchify_fn=batchify_fn,
                                    batch_size=batch_size)
print('Average length of batches is', sum(batch[0][0].shape[1] for batch in data_loader) / len(data_loader))

Average length of batches is 500.0


<img src="../img/fixed_bucket_strategy_ratio0.7.png" style="width: 100%;"/>

##### Custom `Sampler` for `DataLoader`

Sampling random sentences from the Dataset and padding them is sub-optimal as the number of padding elments is determined by the longest sentence.
`DataLoader` supports the specification of a `Sampler` to specify the sentences to select for a batch.

For example, `gluonnlp.data.FixedBucketSampler` assigns each data sample (sentence)
to a fixed bucket based on its length. Resulting batches will only contain sentences
from a single bucket.

This can significantly reduce the average number of elements per batch and consequently the amount of computation.

In [19]:
print(nlp.data.FixedBucketSampler.__doc__)

Assign each data sample to a fixed bucket based on its length.
    The bucket keys are either given or generated from the input sequence lengths.

    Parameters
    ----------
    lengths : list of int or list of tuple/list of int
        The length of the sequences in the input data sample.
    batch_size : int
        The batch size of the sampler.
    num_buckets : int or None, default 10
        The number of buckets. This will not be used if bucket_keys is set.
    bucket_keys : None or list of int or list of tuple, default None
        The keys that will be used to create the buckets. It should usually be the lengths of the
        sequences. If it is None, the bucket_keys will be generated based on the maximum
        lengths of the data.
    ratio : float, default 0
        Ratio to scale up the batch size of smaller buckets.
        Assume the :math:`i` th key is :math:`K_i` ,
        the default batch size is :math:`B` , the ratio to scale the batch size is
        :math:`\a

In [20]:
train_sampler = nlp.data.FixedBucketSampler(
    lengths=train_dataset.transform(lambda x: len(x[0]), lazy=False),
    batch_size=batch_size, shuffle=True)
test_sampler = nlp.data.FixedBucketSampler(
    lengths=test_dataset.transform(lambda x: len(x[0]), lazy=False),
    batch_size=batch_size, shuffle=True)

print(train_sampler.stats())

FixedBucketSampler:
  sample_num=25000, batch_num=201
  key=[59, 108, 157, 206, 255, 304, 353, 402, 451, 500]
  cnt=[1036, 2543, 7173, 4296, 2619, 1729, 1330, 954, 733, 2587]
  batch_size=[128, 128, 128, 128, 128, 128, 128, 128, 128, 128]


In [21]:
train_dataloader = gluon.data.DataLoader(train_dataset, batchify_fn=batchify_fn, batch_sampler=train_sampler)
test_dataloader = gluon.data.DataLoader(test_dataset, batchify_fn=batchify_fn, batch_sampler=test_sampler)
print('Average length of batches is',
      sum(batch[0][0].shape[1] for batch in train_dataloader) / len(train_dataloader))

Average length of batches is 241.4726368159204


In [22]:
next(iter(train_dataloader))

((
  [[2.8570e+03 3.0000e+01 5.3000e+02 ... 1.0000e+00 1.0000e+00 1.0000e+00]
   [5.1000e+01 9.0000e+00 3.4000e+01 ... 1.0000e+00 1.0000e+00 1.0000e+00]
   [2.3600e+02 9.0000e+00 5.5700e+03 ... 1.0000e+00 1.0000e+00 1.0000e+00]
   ...
   [1.4441e+04 1.9962e+04 5.1510e+03 ... 1.0000e+00 1.0000e+00 1.0000e+00]
   [3.9900e+03 1.1000e+01 2.6722e+04 ... 1.0000e+00 1.0000e+00 1.0000e+00]
   [2.8090e+03 8.6000e+01 3.8900e+02 ... 1.0000e+00 1.0000e+00 1.0000e+00]]
  <NDArray 128x353 @cpu_shared(0)>, 
  [342 350 306 305 314 324 352 308 316 313 309 312 309 335 327 317 330 331
   314 341 323 316 330 351 340 353 320 341 338 334 342 350 316 341 337 349
   347 330 317 353 339 344 311 324 307 314 340 341 314 308 338 342 310 310
   327 352 335 317 317 353 317 335 345 350 306 331 340 333 340 333 318 318
   340 317 311 343 307 347 325 308 342 312 312 310 334 332 347 353 313 340
   351 312 320 309 314 344 306 342 309 351 338 310 308 349 323 315 307 340
   341 342 318 326 346 320 321 343 308 306 307 346 3

# Classification Models: Using a Bag of Context Free Embeddings

### Train and Evaluate the Model



In [23]:
def evaluate(test_data, ctx, net):
    accuracy = 0
    ctx = d2l.try_gpu()
    for i, ((inputs, _), labels) in enumerate(test_data):
        inputs = inputs.as_in_context(ctx)
        labels = labels.as_in_context(ctx)
        outs = net(inputs)
        accuracy += (outs.argmax(axis=1).squeeze() == labels).mean()
    print("Test Acc {}".format(accuracy.asscalar()/(i+1)))

In [24]:
def train(net, train_iter, test_iter, loss, trainer, num_epochs, ctx):
    num_batches = len(train_iter)
    params = [p for p in net.collect_params().values() if p.grad_req != 'null']
    for epoch in range(num_epochs):
        accuracy = mx.metric.Accuracy()
        running_loss = 0
        for i, ((features, _), labels) in enumerate(train_iter):           
            features = gluon.utils.split_and_load(features, ctx, even_split=False)
            labels = gluon.utils.split_and_load(labels, ctx, even_split=False)
            losses, preds = [], []
            with mx.autograd.record():
                for feature, label in zip(features, labels):
                    y = net(feature)
                    l = loss(y, label)
                    losses.append(l)
                    preds.append(y)
            mx.autograd.backward(losses)
            for l in losses:
                running_loss += l.mean().asscalar() / len(losses)
            # Gradient clipping
            trainer.allreduce_grads()
            nlp.utils.clip_grad_global_norm(params, 1)
            trainer.update(1)

            accuracy.update(labels, preds)
            if i % 25 == 0:
                print("Batch", i, "Acc", accuracy.get()[1],"Train Loss", running_loss/(i+1))
        print("Epoch {}, Acc {}, Train Loss {}".format(epoch, accuracy.get(), running_loss/(i+1)))
        evaluate(test_iter, ctx, net)

We define a prediction function:

In [25]:
def predict_sentiment(net, vocab, sentence):
    sentence = nd.array(vocab[sentence.split()], ctx=d2l.try_gpu())
    label = nd.argmax(net(sentence.reshape((1, -1))), axis=1)
    return 'positive' if label.asscalar() == 1 else 'negative'

# Using Recurrent Neural Networks

In this section, we will apply
pre-trained word vectors and bidirectional recurrent neural networks with
multiple hidden layers:

Maas, Andrew L., et al. "Learning word vectors for sentiment analysis." Proceedings of the 49th annual meeting of the association for computational linguistics: Human language technologies-volume 1. Association for Computational Linguistics, 2011.

## Bidirectional RNNs

![BiRNN](../img/birnn.svg)


## Use a Recurrent Neural Network Model

In this model, each word first obtains a feature vector from the embedding
layer. Then, we further encode the feature sequence using a bidirectional
recurrent neural network to obtain sequence information. Finally, we transform
the encoded sequence information to output through the fully connected
layer. Specifically, we can concatenate hidden states of bidirectional
long-short term memory in the initial time step and final time step and pass it
to the output layer classification as encoded feature sequence information. In
the `BiRNN` class implemented below, the `Embedding` instance is the embedding
layer, the `LSTM` instance is the hidden layer for sequence encoding, and the
`Dense` instance is the output layer for generated classification results.

In [26]:
class BiRNN(nn.Block):
    def __init__(self, vocab_size, embed_size, num_hiddens, num_layers, **kwargs):
        super(BiRNN, self).__init__(**kwargs)
        self.embedding = nn.Embedding(vocab_size, embed_size)
        # Set Bidirectional to True to get a bidirectional recurrent neural
        # network
        self.encoder = rnn.LSTM(num_hiddens, num_layers=num_layers,
                                bidirectional=True, input_size=embed_size)
        self.decoder = nn.Dense(2)

    def forward(self, inputs):
        # The shape of inputs is (batch size, number of words). Because LSTM
        # needs to use sequence as the first dimension, the input is
        # transformed and the word feature is then extracted. The output shape
        # is (number of words, batch size, word vector dimension).
        embeddings = self.embedding(mx.nd.transpose(inputs))
        # Since the input (embeddings) is the only argument passed into
        # rnn.LSTM, it only returns the hidden states of the last hidden layer
        # at different time step (outputs). The shape of outputs is
        # (number of words, batch size, 2 * number of hidden units).
        outputs = self.encoder(embeddings)
        # Concatenate the hidden states of the initial time step and final
        # time step to use as the input of the fully connected layer. Its
        # shape is (batch size, 4 * number of hidden units)
        encoding = mx.nd.concat(outputs[0], outputs[-1])
        outs = self.decoder(encoding)
        return outs

Create a bidirectional recurrent neural network with two hidden layers.

In [27]:
ctx, embed_size = d2l.try_all_gpus(), 300
num_hiddens, num_layers = 100, 2
net = BiRNN(len(vocab), embed_size, num_hiddens, num_layers)
net.initialize(mx.init.Xavier(), ctx=ctx)

In [28]:
emb = nlp.embedding.create('fasttext', source='wiki.simple', load_ngrams=True)
idx_to_vec = emb[vocab.idx_to_token]
idx_to_vec.shape

(28740, 300)

### Load Pre-trained Word Vectors

Because the training data set for sentiment classification is not very large, in order to deal with overfitting, we will directly use word vectors pre-trained on a larger corpus as the feature vectors of all words. Here, we load a 100-dimensional GloVe word vector for each word in the dictionary `vocab`.

In [29]:
net.embedding.weight.set_data(idx_to_vec)
net.embedding.collect_params().setattr('grad_req', 'null')

### Train and Evaluate the Model

Now, we can start training.

In [30]:
lr, num_epochs = 0.001, 5
trainer = gluon.Trainer(net.collect_params(), 'adam', {'learning_rate': lr}, update_on_kvstore=False)
loss = gluon.loss.SoftmaxCrossEntropyLoss()
train(net, train_dataloader, test_dataloader, loss, trainer, num_epochs, ctx)

Batch 0 Acc 0.484375 Train Loss 0.6938077509403229
Batch 25 Acc 0.5309622102254684 Train Loss 0.6898814967045417
Batch 50 Acc 0.5470152779965349 Train Loss 0.6906460038587159
Batch 75 Acc 0.5764743658353848 Train Loss 0.6739107990441354
Batch 100 Acc 0.5751602564102564 Train Loss 0.6888917897376093
Batch 125 Acc 0.5853893600616809 Train Loss 0.6879730587086034
Batch 150 Acc 0.6071733105947559 Train Loss 0.6707309216556959
Batch 175 Acc 0.6205403927643869 Train Loss 0.6583679692650383
Batch 200 Acc 0.62748 Train Loss 0.6586800434844411
Epoch 0, Acc ('accuracy', 0.62748), Train Loss 0.6586800434844411
Test Acc 0.6838696350404365
Batch 0 Acc 0.7265625 Train Loss 0.6703384667634964
Batch 25 Acc 0.6577139287945034 Train Loss 0.6076179347359217
Batch 50 Acc 0.6851409460105112 Train Loss 0.619041949729709
Batch 75 Acc 0.7036482293784102 Train Loss 0.5970501465918986
Batch 100 Acc 0.715230732446003 Train Loss 0.5821028100603288
Batch 125 Acc 0.7088997178763785 Train Loss 0.5854523529904703
Bat

In [31]:
predict_sentiment(net, vocab, 'this movie is so great')

'positive'

In [32]:
predict_sentiment(net, vocab, 'this movie is so bad')

'negative'

# Using Convolutional Neural Networks (textCNN)

Idea: treat text as a one-dimensional "image".

Then we can use one-dimensional convolutional neural networks to capture associations between adjacent words.

This section describes a groundbreaking approach to applying
convolutional neural networks to text analysis: textCNN :cite:`Kim.2014`.

## One-dimensional Convolutional Layer

![One-dimensional cross-correlation operation. The shaded parts are the first output element as well as the input and kernel array elements used in its calculation: $0\times1+1\times2=2$. ](../img/conv1d.svg)

Before introducing the model, let us explain how a one-dimensional convolutional layer works. Like a two-dimensional convolutional layer, a one-dimensional convolutional layer uses a one-dimensional cross-correlation operation. In the one-dimensional cross-correlation operation, the convolution window starts from the leftmost side of the input array and slides on the input array from left to right successively. When the convolution window slides to a certain position, the input subarray in the window and kernel array are multiplied and summed by element to get the element at the corresponding location in the output array. As shown in Figure 12.4, the input is a one-dimensional array with a width of 7 and the width of the kernel array is 2. As we can see, the output width is $7-2+1=6$ and the first element is obtained by performing multiplication by element on the leftmost input subarray with a width of 2 and kernel array and then summing the results.


Next, we implement one-dimensional cross-correlation in the `corr1d` function. It accepts the input array `X` and kernel array `K` and outputs the array `Y`.

In [33]:
def corr1d(X, K):
    w = K.shape[0]
    Y = nd.zeros((X.shape[0] - w + 1))
    for i in range(Y.shape[0]):
        Y[i] = (X[i: i + w] * K).sum()
    return Y

Let's reproduce the results of the one-dimensional cross-correlation operation seen in above Figure.

In [34]:
X, K = nd.array([0, 1, 2, 3, 4, 5, 6]), nd.array([1, 2])
corr1d(X, K)


[ 2.  5.  8. 11. 14. 17.]
<NDArray 6 @cpu(0)>

## One-dimensional Convolutional Layer with multiple input channels


![One-dimensional cross-correlation operation with three input channels. The shaded parts are the first output element as well as the input and kernel array elements used in its calculation: $0\times1+1\times2+1\times3+2\times4+2\times(-1)+3\times(-3)=2$. ](../img/conv1d-channel.svg)

The one-dimensional cross-correlation operation for multiple input channels is also similar to the two-dimensional cross-correlation operation for multiple input channels. On each channel, it performs the one-dimensional cross-correlation operation on the kernel and its corresponding input and adds the results of the channels to get the output. Figure 12.5 shows a one-dimensional cross-correlation operation with three input channels.

Now, we reproduce the results of the one-dimensional cross-correlation operation with multi-input channel.

In [35]:
def corr1d_multi_in(X, K):
    return nd.add_n(*[corr1d(x, k) for x, k in zip(X, K)])

In [36]:
X = nd.array([[0, 1, 2, 3, 4, 5, 6],
              [1, 2, 3, 4, 5, 6, 7],
              [2, 3, 4, 5, 6, 7, 8]])
K = nd.array([[1, 2], [3, 4], [-1, -3]])
corr1d_multi_in(X, K)


[ 2.  8. 14. 20. 26. 32.]
<NDArray 6 @cpu(0)>

This is equivalent to two-dimensional cross-correlation with a single input channel

![Two-dimensional cross-correlation operation with a single input channel. The highlighted parts are the first output element and the input and kernel array elements used in its calculation: $2\times(-1)+3\times(-3)+1\times3+2\times4+0\times1+1\times2=2$. ](../img/conv1d-2d.svg)

We can obtain multiple output channels by applying the cross-correlation multiple times with different kernels.

## Max-Over-Time Pooling Layer

Similarly, we have a one-dimensional pooling layer. The max-over-time pooling layer used in TextCNN actually corresponds to a one-dimensional global maximum pooling layer. Assuming that the input contains multiple channels, and each channel consists of values on different time steps, the output of each channel will be the largest value of all time steps in the channel. Therefore, the input of the max-over-time pooling layer can have different time steps on each channel.

To improve computing performance, we often combine timing examples of different lengths into a mini-batch and make the lengths of each timing example in the batch consistent by appending special characters (such as 0) to the end of shorter examples. Naturally, the added special characters have no intrinsic meaning. Because the main purpose of the max-over-time pooling layer is to capture the most important features of timing, it usually allows the model to be unaffected by the manually added characters.

## The TextCNN Model

![TextCNN design. ](../img/textcnn.svg)

Kim, Yoon. "Convolutional neural networks for sentence classification." EMNLP 2014.

TextCNN mainly uses a one-dimensional convolutional layer and max-over-time pooling layer. Suppose the input text sequence consists of $n$ words, and each word is represented by a $d$-dimension word vector. Then the input example has a width of $n$, a height of 1, and $d$ input channels. The calculation of textCNN can be mainly divided into the following steps:

1. Define multiple one-dimensional convolution kernels and use them to perform convolution calculations on the inputs. Convolution kernels with different widths may capture the correlation of different numbers of adjacent words.
2. Perform max-over-time pooling on all output channels, and then concatenate the pooling output values of these channels in a vector.
3. The concatenated vector is transformed into the output for each category through the fully connected layer. A dropout layer can be used in this step to deal with overfitting.

Figure 12.7 gives an example to illustrate the textCNN. The input here is a sentence with 11 words, with each word represented by a 6-dimensional word vector. Therefore, the input sequence has a width of 11 and 6 input channels. We assume there are two one-dimensional convolution kernels with widths of 2 and 4, and 4 and 5 output channels, respectively. Therefore, after one-dimensional convolution calculation, the width of the four output channels is $11-2+1=10$, while the width of the other five channels is $11-4+1=8$. Even though the width of each channel is different, we can still perform max-over-time pooling for each channel and concatenate the pooling outputs of the 9 channels into a 9-dimensional vector. Finally, we use a fully connected layer to transform the 9-dimensional vector into a 2-dimensional output: positive sentiment and negative sentiment predictions.

Next, we will implement a textCNN model. Compared with the previous section, in addition to replacing the recurrent neural network with a one-dimensional convolutional layer, here we use two embedding layers, one with a fixed weight and another that participates in training.

In [37]:
class TextCNN(nn.Block):
    def __init__(self, vocab_size, embed_size, kernel_sizes, num_channels,
                 **kwargs):
        super(TextCNN, self).__init__(**kwargs)
        self.embedding = nn.Embedding(vocab_size, embed_size)
        # The embedding layer does not participate in training
        self.constant_embedding = nn.Embedding(vocab_size, embed_size)
        self.dropout = nn.Dropout(0.5)
        self.decoder = nn.Dense(2)
        # The max-over-time pooling layer has no weight, so it can share an
        # instance
        self.pool = nn.GlobalMaxPool1D()
        # Create multiple one-dimensional convolutional layers
        self.convs = nn.Sequential()
        for c, k in zip(num_channels, kernel_sizes):
            self.convs.add(nn.Conv1D(c, k, activation='relu'))

    def forward(self, inputs):
        # Concatenate the output of two embedding layers with shape of
        # (batch size, number of words, word vector dimension) by word vector
        embeddings = nd.concat(
            self.embedding(inputs), self.constant_embedding(inputs), dim=2)
        # According to the input format required by Conv1D, the word vector
        # dimension, that is, the channel dimension of the one-dimensional
        # convolutional layer, is transformed into the previous dimension
        embeddings = embeddings.transpose((0, 2, 1))
        # For each one-dimensional convolutional layer, after max-over-time
        # pooling, an NDArray with the shape of (batch size, channel size, 1)
        # can be obtained. Use the flatten function to remove the last
        # dimension and then concatenate on the channel dimension
        encoding = nd.concat(*[nd.flatten(
            self.pool(conv(embeddings))) for conv in self.convs], dim=1)
        # After applying the dropout method, use a fully connected layer to
        # obtain the output
        outputs = self.decoder(self.dropout(encoding))
        return outputs

Create a TextCNN instance. It has 3 convolutional layers with kernel widths of 3, 4, and 5, all with 100 output channels.

In [38]:
kernel_sizes, nums_channels = [3, 4, 5], [100, 100, 100]
net = TextCNN(len(vocab), embed_size, kernel_sizes, nums_channels)
net.initialize(mx.init.Xavier(), ctx=ctx)

### Load Pre-trained Word Vectors

As in the previous section, load pre-trained 100-dimensional GloVe word vectors and initialize the embedding layers `embedding` and `constant_embedding`. Here, the former participates in training while the latter has a fixed weight.

In [39]:
net.embedding.weight.set_data(idx_to_vec)
net.constant_embedding.weight.set_data(idx_to_vec)
net.constant_embedding.collect_params().setattr('grad_req', 'null')

### Train and Evaluate the Model

Now we can train the model.

In [40]:
lr, num_epochs = 0.001, 5
trainer = gluon.Trainer(net.collect_params(), 'adam', {'learning_rate': lr}, update_on_kvstore=False)
loss = gluon.loss.SoftmaxCrossEntropyLoss()
train(net, train_dataloader, test_dataloader, loss, trainer, num_epochs, ctx)

Batch 0 Acc 0.4453125 Train Loss 0.9054063707590103
Batch 25 Acc 0.5721301411909147 Train Loss 0.8247966115864424
Batch 50 Acc 0.6376073814826598 Train Loss 0.6877362090436852
Batch 75 Acc 0.6810400171196234 Train Loss 0.6127394276278976
Batch 100 Acc 0.7012353706111834 Train Loss 0.5858116941618743
Batch 125 Acc 0.718857068976663 Train Loss 0.559216885797916
Batch 150 Acc 0.7330869355616262 Train Loss 0.536362633614844
Batch 175 Acc 0.7438990825688073 Train Loss 0.5186570233940571
Batch 200 Acc 0.75528 Train Loss 0.501863587008261
Epoch 0, Acc ('accuracy', 0.75528), Train Loss 0.501863587008261
Test Acc 0.8459488758489714
Batch 0 Acc 0.8828125 Train Loss 0.3133721239864826
Batch 25 Acc 0.8690513219284604 Train Loss 0.31316623378258485
Batch 50 Acc 0.8682774746687452 Train Loss 0.3106932615240415
Batch 75 Acc 0.8731038811591171 Train Loss 0.30155029309619413
Batch 100 Acc 0.8737256161194509 Train Loss 0.29962366422878045
Batch 125 Acc 0.8733560017963687 Train Loss 0.29981191642582417
B

Below, we use the trained model to the classify sentiments of two simple sentences.

In [41]:
predict_sentiment(net, vocab, 'this movie is so great')

'negative'

In [42]:
predict_sentiment(net, vocab, 'this movie is so bad')

'negative'