# Manipulating Data with `NDArray`

In [1]:
import d2l
import mxnet as mx
from mxnet import nd

Let's create a 2D array (matrix) from scratch.

In [2]:
# set ctx=mx.gpu(0) to create one on a GPU
a = nd.array(((1,2,3),(5,6,7)), ctx=mx.cpu())
a


[[1. 2. 3.]
 [5. 6. 7.]]
<NDArray 2x3 @cpu(0)>

Array of ones

In [3]:
ones = nd.ones((2,3))
ones


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

Array of random variables

In [4]:
rand_uniform = nd.random.uniform(-1,1,shape=(3,3))
rand_uniform


[[ 0.09762704  0.18568921  0.43037868]
 [ 0.6885315   0.20552671  0.71589124]
 [ 0.08976638  0.6945034  -0.15269041]]
<NDArray 3x3 @cpu(0)>

In [5]:
twos = nd.full((2,3), 2.0)
twos


[[2. 2. 2.]
 [2. 2. 2.]]
<NDArray 2x3 @cpu(0)>

Inspect an NDArray's attributes: `shape`, `size` and `dtype`.

In [6]:
(a.shape, a.size, a.dtype, a.context)

((2, 3), 6, numpy.float32, cpu(0))

## Operations

* Pointwise multiplication:

In [7]:
twos = nd.full((2,3), 2.0)
a * twos


[[ 2.  4.  6.]
 [10. 12. 14.]]
<NDArray 2x3 @cpu(0)>

* Exponentiation

In [8]:
twos.exp()


[[7.389056 7.389056 7.389056]
 [7.389056 7.389056 7.389056]]
<NDArray 2x3 @cpu(0)>

### Matrix Multiplications

In [9]:
nd.dot(a, a.T)


[[ 14.  38.]
 [ 38. 110.]]
<NDArray 2x2 @cpu(0)>

**Indexing** works just like in NumPy. 

In [10]:
print(a[1,2])
print(a[-1])
print(a[:,1:3])
a[:,1:3] = 2
print(a)


[7.]
<NDArray 1 @cpu(0)>

[5. 6. 7.]
<NDArray 3 @cpu(0)>

[[2. 3.]
 [6. 7.]]
<NDArray 2x2 @cpu(0)>

[[1. 2. 2.]
 [5. 2. 2.]]
<NDArray 2x3 @cpu(0)>


### Converting between MXNet NDArray and NumPy

Converting MXNet NDArrays to and from NumPy is easy. The converted arrays do not share memory.

In [11]:
x = a.asnumpy()
(type(x), x)

(numpy.ndarray, array([[1., 2., 2.],
        [5., 2., 2.]], dtype=float32))

In [12]:
nd.array(x);

### Deferred and asynchronous execution

Code will be executed not by Python but by the MXNet engine. This means that operations return immediately. Only when accessing the result will it block.

In [13]:
x = nd.random.uniform(-1,1,shape=(1024,1024))
y = nd.random.uniform(-1,1,shape=(1024,1024))

timer = d2l.Timer()
for i in range(100):
    z = nd.dot(x,y)

print('Workloads are queued. Time %.4f sec' % timer.stop())
z[0,0].asnumpy();
print('Workloads are done. Time %.4f sec' % timer.stop())

Workloads are queued. Time 0.0044 sec
Workloads are done. Time 0.8841 sec
